<script>
  import { app } from '$lib/state.svelte.js';
  import { runChecklist } from '$lib/checklist.js';

  const checks = $derived(runChecklist(app.figmaProperties, app.webProperties));
  const passed = $derived(checks ? checks.filter(c => !c.skip && c.pass).length : 0);
  const applicable = $derived(checks ? checks.filter(c => !c.skip).length : 0);

  let copyMsg = $state('');

  function buildReport() {
    if (!checks) return '';
    let txt = `Loupe Inspect — ${passed}/${applicable} checks pass\n`;
    txt += '='.repeat(40) + '\n\n';
    for (const c of checks) {
      if (c.skip) continue;
      const icon = c.pass ? '[PASS]' : '[FAIL]';
      txt += `${icon} ${c.label}\n`;
      if (!c.pass && c.figmaVal && c.webVal) {
        txt += `       Figma: ${c.figmaVal}\n`;
        txt += `       Web:   ${c.webVal}\n`;
      }
    }
    txt += `\n— Generated by Loupe\n`;
    return txt;
  }

  async function copyReport() {
    await navigator.clipboard.writeText(buildReport());
    copyMsg = 'Copied!';
    setTimeout(() => copyMsg = '', 2000);
  }
</script>

<div class="inspect-tab">
  <p class="tab-desc">Design fidelity checklist — does the web implementation match the Figma design?</p>

  {#if !app.figmaProperties || !app.webProperties}
    <div class="empty-state">
      <div class="icon">
        <svg width="48" height="48" viewBox="0 0 48 48" fill="none">
          <rect x="4" y="8" width="18" height="32" rx="3" stroke="currentColor" stroke-width="2" fill="none"/>
          <rect x="26" y="8" width="18" height="32" rx="3" stroke="currentColor" stroke-width="2" fill="none"/>
          <path d="M14 20h-2m2 4h-2m2 4h-2" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
          <path d="M36 20h-2m2 4h-2m2 4h-2" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
        </svg>
      </div>
      {#if !app.figmaProperties && !app.webProperties}
        <h2>No properties to compare</h2>
        <p>Capture a Figma frame and a web element first. Properties are extracted automatically during capture.</p>
      {:else}
        <h2>Waiting for both captures</h2>
        <p>
          {#if !app.figmaProperties}Figma properties not yet received.{/if}
          {#if !app.webProperties}Web properties not yet captured.{/if}
        </p>
      {/if}
      <div class="empty-links">
        {#if !app.figmaProperties}
          <button class="btn-link" onclick={() => app.activeTab = 0}>Go to Figma</button>
        {/if}
        {#if !app.webProperties}
          <button class="btn-link" onclick={() => app.activeTab = 1}>Go to Web</button>
        {/if}
      </div>
    </div>
  {:else if checks}
    <div class="score-bar">
      <span class="score-label">{passed} of {applicable} checks pass</span>
      {#if applicable > 0}
        <span class="score-pct" class:good={passed / applicable >= 0.8} class:warn={passed / applicable >= 0.5 && passed / applicable < 0.8} class:bad={passed / applicable < 0.5}>
          {Math.round(passed / applicable * 100)}%
        </span>
      {/if}
    </div>

    <div class="checklist">
      {#each checks as check}
        {#if !check.skip}
          <div class="check-item" class:check-pass={check.pass} class:check-fail={!check.pass}>
            <span class="check-icon">{check.pass ? '\u2713' : '\u2717'}</span>
            <div class="check-body">
              <span class="check-label">{check.label}</span>
              {#if !check.pass && check.figmaVal && check.webVal}
                <div class="check-detail">
                  <span class="detail-tag figma">Figma</span>
                  <span class="detail-val">{check.figmaVal}</span>
                  <span class="detail-tag web">Web</span>
                  <span class="detail-val">{check.webVal}</span>
                </div>
              {/if}
              {#if check.note}
                <span class="check-note">{check.note}</span>
              {/if}
            </div>
          </div>
        {/if}
      {/each}
    </div>

    <div class="actions">
      <button class="btn-copy" onclick={copyReport}>Copy Report</button>
      {#if copyMsg}
        <span class="copy-msg">{copyMsg}</span>
      {/if}
    </div>
  {/if}
</div>

<style>
  .inspect-tab {
    display: flex;
    flex-direction: column;
    height: 100%;
    min-height: 400px;
  }

  .tab-desc {
    font-size: 13px;
    color: #6b7280;
    margin: 0 0 12px;
  }

  /* Empty state */
  .empty-state {
    text-align: center;
    color: #6b7280;
    margin: auto;
  }

  .empty-state .icon { color: #d1d5db; margin-bottom: 16px; }

  .empty-state h2 {
    font-size: 18px;
    font-weight: 600;
    color: #374151;
    margin: 0 0 8px;
  }

  .empty-state p {
    font-size: 14px;
    margin: 0 0 16px;
    max-width: 400px;
  }

  .empty-links { display: flex; gap: 8px; justify-content: center; }

  .btn-link {
    padding: 8px 16px;
    font-size: 14px;
    font-weight: 500;
    border: 1px solid #6366f1;
    border-radius: 8px;
    background: transparent;
    color: #6366f1;
    cursor: pointer;
  }

  .btn-link:hover { background: rgba(99, 102, 241, 0.05); }

  /* Score bar */
  .score-bar {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 14px 18px;
    background: #f3f4f6;
    border-radius: 10px;
    margin-bottom: 16px;
  }

  .score-label {
    font-size: 15px;
    font-weight: 600;
    color: #374151;
  }

  .score-pct {
    font-size: 22px;
    font-weight: 700;
    border-radius: 8px;
    padding: 4px 14px;
  }

  .score-pct.good { color: #16a34a; background: #f0fdf4; }
  .score-pct.warn { color: #d97706; background: #fffbeb; }
  .score-pct.bad { color: #dc2626; background: #fef2f2; }

  /* Checklist */
  .checklist {
    flex: 1;
    overflow: auto;
    display: flex;
    flex-direction: column;
    gap: 6px;
  }

  .check-item {
    display: flex;
    align-items: flex-start;
    gap: 12px;
    padding: 12px 14px;
    border-radius: 10px;
    border: 1px solid #e5e7eb;
  }

  .check-item.check-pass {
    background: #f0fdf4;
    border-color: #bbf7d0;
  }

  .check-item.check-fail {
    background: #fef2f2;
    border-color: #fecaca;
  }

  .check-icon {
    font-size: 18px;
    font-weight: 700;
    line-height: 1;
    flex-shrink: 0;
    width: 24px;
    text-align: center;
  }

  .check-pass .check-icon { color: #16a34a; }
  .check-fail .check-icon { color: #dc2626; }

  .check-body {
    flex: 1;
    min-width: 0;
  }

  .check-label {
    font-size: 14px;
    font-weight: 600;
    color: #111827;
    display: block;
  }

  .check-detail {
    display: flex;
    align-items: center;
    gap: 6px;
    flex-wrap: wrap;
    margin-top: 6px;
    font-size: 12px;
    font-family: 'SF Mono', Monaco, Consolas, monospace;
  }

  .detail-tag {
    font-size: 10px;
    font-weight: 600;
    padding: 1px 6px;
    border-radius: 4px;
    text-transform: uppercase;
    letter-spacing: 0.04em;
    flex-shrink: 0;
  }

  .detail-tag.figma { background: #ede9fe; color: #7c3aed; }
  .detail-tag.web { background: #e0f2fe; color: #0369a1; }

  .detail-val {
    color: #4b5563;
    word-break: break-all;
  }

  .check-note {
    display: block;
    margin-top: 4px;
    font-size: 12px;
    color: #9ca3af;
    font-style: italic;
  }

  /* Actions */
  .actions {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-top: 12px;
    flex-shrink: 0;
  }

  .btn-copy {
    padding: 8px 16px;
    font-size: 13px;
    font-weight: 500;
    border: 1px solid #6366f1;
    border-radius: 8px;
    background: transparent;
    color: #6366f1;
    cursor: pointer;
  }

  .btn-copy:hover { background: rgba(99, 102, 241, 0.06); }

  .copy-msg {
    font-size: 12px;
    color: #16a34a;
    font-weight: 500;
  }

  @media (prefers-color-scheme: dark) {
    .tab-desc { color: #9ca3af; }
    .empty-state h2 { color: #e5e7eb; }
    .empty-state .icon { color: #4b5563; }
    .btn-link { border-color: #818cf8; color: #818cf8; }
    .score-bar { background: #1f2937; }
    .score-label { color: #d1d5db; }
    .score-pct.good { color: #4ade80; background: #052e16; }
    .score-pct.warn { color: #fbbf24; background: #422006; }
    .score-pct.bad { color: #f87171; background: #450a0a; }
    .check-item { border-color: #374151; }
    .check-item.check-pass { background: #052e16; border-color: #16a34a; }
    .check-item.check-fail { background: #450a0a; border-color: #dc2626; }
    .check-label { color: #e5e7eb; }
    .detail-tag.figma { background: #2e1065; color: #c4b5fd; }
    .detail-tag.web { background: #0c4a6e; color: #7dd3fc; }
    .detail-val { color: #9ca3af; }
    .check-note { color: #6b7280; }
    .btn-copy { border-color: #818cf8; color: #818cf8; }
    .copy-msg { color: #4ade80; }
  }
</style>
